### PR TITLE
Create check-service.sh

### PR DESCRIPTION
**Pull request by secobau**

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
What's this for?

**Comment by secobau** [comment]
Automatically testing any change in the code.

**Comment by alejandro-colomar** [comment]
How should i use this script to automatically test changes?

**Comment by secobau** [comment]
Github will do it.

**Comment by secobau** [comment]
It is a script for Github.

**Comment by alejandro-colomar** [comment]
Where is github configured to use this script?

**Comment by alejandro-colomar** [comment]
The real question is why did you separate in 2 PRs two files that need eachother.

**Comment by secobau** [comment]
> The real question is why did you separate in 2 PRs two files that need eachother.

That would make sense but it is already done.

**Pull request merged**
